### ISSUE TITLE
Build Warnings on dashboard

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerMarkupsToModel#12]
http://slicer.cdash.org/viewBuildError.php?type=1&buildid=1117129

@lassoan I believe I've fixed most of these, but I don't know where to begin with this one:
> make[7]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.

Do you have any suggestion where I should look?

**Comment by lassoan** [comment]
> make[7]: warning: jobserver unavailable: using -j1. Add `+' to parent make rule.

This is not a problem in the extension's source code.
