### ISSUE TITLE
Using Markups to Models module from python interactor

### ISSUE THREAD

**Issue by mpontin93** [SlicerIGT/SlicerMarkupsToModel#30]
Hello everybody,
I'm trying to create a cylinder based on a user defined fiducial. The fiducial should be the center point of the base of the cylinder.
Using a python script I developed, I managed to setup all the fiducials I need in order to create the cylinder using the Markups to Models module. Now I'd like to automatically call the module from within the script, passing all the parameters I need. Is it possible?
Also, maybe I'm approaching the problem the wrong way; do you have any viable alternatives?
Thank you very much for the help
Marco

**Comment by lassoan** [comment]
Let's keep the discussion on discourse, many more people can join the discussion there.
