### ISSUE TITLE
Rename to SlicerPointsToModel

### ISSUE THREAD

**Issue by tavaughan** [SlicerIGT/SlicerMarkupsToModel#4]
To consider farther down the road, when this model takes other types of input in addition to markups fiducials

**Comment by tavaughan** [comment]
@lassoan Do we want to proceed with this rename? I imagine this would have some consequences since there are a few projects that depend on "SlicerMarkupsToModel"

**Comment by lassoan** [comment]
MarkupsToModel packages will be kept in the extension manager.

For new nightly builds, I'll check all the extensions in the extension manager to see what uses MarkupsToModel. Depending on what we find, we may need to keep both the old and the new extension alive, or just simply switch.

**Comment by tavaughan** [comment]
Ok, thanks! Let me know!

**Comment by tavaughan** [comment]
I'm guessing there are more extensions now that use SlicerMarkupsToModel. Do we want to just abandon this idea?

**Comment by tavaughan** [comment]
@lassoan

**Comment by lassoan** [comment]
Wait for a better opportunity to rename the extension (when users would benefit from it, not just frustrated by the change).
